### ISSUE TITLE
此方案存在的两个问题

### ISSUE THREAD

**Issue by Blankeer** [lifetyper/alipay_fetcher#1]
挂着测试的一段时间，发现的问题：
1. 挂一段时候后，会重定向到 www.alipay.com，猜测是频率问题，过段时间恢复正常，不是cookie过期，重新登录也不行。
2. 该账单页面，默认只显示20条数据，如果一分钟订单数>20，会漏单，看了下网络请求，直接请求的话，几个参数被加密了，只能 selenium 模拟翻页抓取数据。

**Comment by lifetyper** [comment]
1.其实我只是提供个框架，主要解决一下模拟登录的问题，重定向这个问题我暂时没观察到，不知道你这个是挂了多久发现的？
2.一分钟订单数>20的话，建议开当面付，我这真的只是个很简陋的东西。
